feat: add time range filter for dagger parquet source
odpf/dagger pull request #147
Opened 2022-05-04 09:39 UTC by prakharmathur82

2022-05-11 06:09 UTC, Meghajit requested changes

2022-05-11 06:13 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRange.java
> +        return instant.equals(startInstant) || instant.equals(endInstant) || (instant.isAfter(startInstant) && instant.isBefore(endInstant));
yes we are explicitly making it inclusive

2022-05-11 06:13 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRange.java
> +        return instant.equals(startInstant) || instant.equals(endInstant) || (instant.isAfter(startInstant) && instant.isBefore(endInstant));
yes we are explicitly making it inclusive

2022-05-11 06:13 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +            if (timestamps.length == 2) {
a range should always have two values

2022-05-11 06:13 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +            if (timestamps.length == 2) {
a range should always have two values

2022-05-11 06:14 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRanges.java
> +public class TimeRanges implements Serializable {
it is already a plural right?

2022-05-11 06:14 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRanges.java
> +public class TimeRanges implements Serializable {
it is already a plural right?

2022-05-11 06:53 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRanges.java
> +public class TimeRanges implements Serializable {
https://medium.com/swlh/an-opinionated-guide-to-naming-your-code-aimed-at-new-developers-6f769d60e098#:~:text=If%20your%20class%20is%20a%20container%20for%20several%20notes%2C%20then%20you%20should%20find%20a%20singular%20noun%20to%20describe%20the%20whole%20thing.

2022-05-12 08:56 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +                if (startTime.isAfter(endTime)) {
Understood that it will be allowed.

2022-05-12 08:57 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/parquet/splitassigner/ChronologyOrderedSplitAssigner.java
> +            if (timeRanges == null || timeRanges.contains(instant)) {
There are unit tests in ChronologyOrderedSplitAssignerTest which implicitly cover this

2022-05-12 08:57 UTC, Meghajit commented
Resolved the conversations which were discussed.

2022-05-13 10:08 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRanges.java
> +public class TimeRanges implements Serializable {
making it TimeRangePool

2022-05-13 10:08 UTC, prakharmathur82 commented on dagger-core/src/main/java/io/odpf/dagger/core/source/parquet/splitassigner/ChronologyOrderedSplitAssigner.java
> +        if (pathParser == null) {
sure

2022-05-13 11:16 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/models/TimeRanges.java
> +public class TimeRanges implements Serializable {
Verified

2022-05-13 11:16 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/parquet/splitassigner/ChronologyOrderedSplitAssigner.java
> +        if (pathParser == null) {
Verified

2022-05-13 11:16 UTC, Meghajit approved these changes

2022-05-24 05:39 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        Date dateTime;
There is no need for this uninitialized variable. You can directly do `parse(timestamp, utcDateFormat).toInstant()` and `parse(timestamp, localDateFormat).toInstant()` in line 56 and 58 respectively.

2022-05-24 05:55 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        } else {
This else block is not needed. Just directly throw the exception after inlining the return statements in 56 and 58 above. Line 54 and 63 can be deleted.

2022-05-24 05:55 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        if (timestamp.length() == utcDateFormatPattern.replace("'", "").length()) {
We seem to be doing multiple things in this if block causing it to look ugly. 
Can we move the `replace` method call up above just below line 48 and just compare lengths here ?

2022-05-24 05:55 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        } else if (timestamp.length() == localDataFormatPattern.replace("'", "").length()) {
same as above

2022-05-24 05:55 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        }
yyyy-MM-dd'T'HH:mm:ssZ should be replaced with `yyyy-MM-ddTHH:mm:ssZ` 
yyyy-MM-dd'T'HH:mm:ss should be replaced with `yyyy-MM-ddTHH:mm:ss`

User should not be expected to provided quotes before and after T in the config

2022-05-24 11:37 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        Date dateTime;
Discussed and agreed that can be skipped

2022-05-24 11:37 UTC, Meghajit commented on dagger-core/src/main/java/io/odpf/dagger/core/source/config/adapter/FileDateRangeAdaptor.java
> +        } else {
Discussed and agreed that this can be skipped

2022-05-24 11:42 UTC, merged